// Generated by CoffeeScript 1.7.1
(function() {
  exports.index = function(req, res) {
    return res.render("index", {
      title: "Lightside Set-Up",
      description: "This is our project base"
    });
  };

  return;

}).call(this);

//# sourceMappingURL=index.map
