// Generated by CoffeeScript 1.7.1
(function() {
  exports.index = function(req, res) {
    return res.render("index", {
      title: "Visualize the Light Side",
      description: ""
    });
  };

  return;

}).call(this);

//# sourceMappingURL=index.map
